export const countries = [
  {
    name: 'Afghanistan',
    cca2: 'AF',
    flag: '🇦🇫',
    code: '+93',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Angola',
    cca2: 'AO',
    flag: '🇦🇴',
    code: '+244',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Albania',
    cca2: 'AL',
    flag: '🇦🇱',
    code: '+355',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Andorra',
    cca2: 'AD',
    flag: '🇦🇩',
    code: '+376',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'United Arab Emirates',
    cca2: 'AE',
    flag: '🇦🇪',
    code: '+971',
    phoneMasks: ['# ### ####', '## ### ####'],
  },
  {
    name: 'Argentina',
    cca2: 'AR',
    flag: '🇦🇷',
    code: '+54',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Armenia',
    cca2: 'AM',
    flag: '🇦🇲',
    code: '+374',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Antigua and Barbuda',
    cca2: 'AG',
    flag: '🇦🇬',
    code: '+1',
    phoneMasks: ['268 ### ####'],
  },
  {
    name: 'Australia',
    cca2: 'AU',
    flag: '🇦🇺',
    code: '+61',
    phoneMasks: ['# #### ####'],
  },
  {
    name: 'Austria',
    cca2: 'AT',
    flag: '🇦🇹',
    code: '+43',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Azerbaijan',
    cca2: 'AZ',
    flag: '🇦🇿',
    code: '+994',
    phoneMasks: ['## ### ## ##'],
  },
  {
    name: 'Burundi',
    cca2: 'BI',
    flag: '🇧🇮',
    code: '+257',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Belgium',
    cca2: 'BE',
    flag: '🇧🇪',
    code: '+32',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Benin',
    cca2: 'BJ',
    flag: '🇧🇯',
    code: '+229',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Burkina Faso',
    cca2: 'BF',
    flag: '🇧🇫',
    code: '+226',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Bangladesh',
    cca2: 'BD',
    flag: '🇧🇩',
    code: '+880',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Bulgaria',
    cca2: 'BG',
    flag: '🇧🇬',
    code: '+359',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Bahrain',
    cca2: 'BH',
    flag: '🇧🇭',
    code: '+973',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Bahamas',
    cca2: 'BS',
    flag: '🇧🇸',
    code: '+1',
    phoneMasks: ['242 ### ####'],
  },
  {
    name: 'Bosnia and Herzegovina',
    cca2: 'BA',
    flag: '🇧🇦',
    code: '+387',
    phoneMasks: ['## ####', '## #####'],
  },
  {
    name: 'Belarus',
    cca2: 'BY',
    flag: '🇧🇾',
    code: '+375',
    phoneMasks: ['## ### ## ##'],
  },
  {
    name: 'Belize',
    cca2: 'BZ',
    flag: '🇧🇿',
    code: '+501',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Bolivia',
    cca2: 'BO',
    flag: '🇧🇴',
    code: '+591',
    phoneMasks: ['# ### ####'],
  },
  {
    name: 'Brazil',
    cca2: 'BR',
    flag: '🇧🇷',
    code: '+55',
    phoneMasks: ['## ##### ####'],
  },
  {
    name: 'Barbados',
    cca2: 'BB',
    flag: '🇧🇧',
    code: '+1',
    phoneMasks: ['246 ### ####'],
  },
  {
    name: 'Brunei',
    cca2: 'BN',
    flag: '🇧🇳',
    code: '+673',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Bhutan',
    cca2: 'BT',
    flag: '🇧🇹',
    code: '+975',
    phoneMasks: ['# ### ###'],
  },
  {
    name: 'Botswana',
    cca2: 'BW',
    flag: '🇧🇼',
    code: '+267',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Central African Republic',
    cca2: 'CF',
    flag: '🇨🇫',
    code: '+236',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Canada',
    cca2: 'CA',
    flag: '🇨🇦',
    code: '+1',
    phoneMasks: [
      '204 ### ####',
      '226 ### ####',
      '236 ### ####',
      '249 ### ####',
      '250 ### ####',
      '289 ### ####',
      '306 ### ####',
      '343 ### ####',
      '365 ### ####',
      '403 ### ####',
      '416 ### ####',
      '418 ### ####',
      '431 ### ####',
      '437 ### ####',
      '438 ### ####',
      '450 ### ####',
      '506 ### ####',
      '514 ### ####',
      '519 ### ####',
      '579 ### ####',
      '581 ### ####',
      '587 ### ####',
      '604 ### ####',
      '613 ### ####',
      '639 ### ####',
      '647 ### ####',
      '705 ### ####',
      '709 ### ####',
      '778 ### ####',
      '780 ### ####',
      '807 ### ####',
      '819 ### ####',
      '867 ### ####',
      '873 ### ####',
      '902 ### ####',
      '905 ### ####',
    ],
  },
  {
    name: 'Switzerland',
    cca2: 'CH',
    flag: '🇨🇭',
    code: '+41',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Chile',
    cca2: 'CL',
    flag: '🇨🇱',
    code: '+56',
    phoneMasks: ['# #### ####'],
  },
  {
    name: 'China',
    cca2: 'CN',
    flag: '🇨🇳',
    code: '+86',
    phoneMasks: ['### #### ###', '### #### ####', '## ##### #####'],
  },
  {
    name: 'Ivory Coast',
    cca2: 'CI',
    flag: '🇨🇮',
    code: '+225',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Cameroon',
    cca2: 'CM',
    flag: '🇨🇲',
    code: '+237',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'DR Congo',
    cca2: 'CD',
    flag: '🇨🇩',
    code: '+243',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Republic of the Congo',
    cca2: 'CG',
    flag: '🇨🇬',
    code: '+242',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Colombia',
    cca2: 'CO',
    flag: '🇨🇴',
    code: '+57',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Comoros',
    cca2: 'KM',
    flag: '🇰🇲',
    code: '+269',
    phoneMasks: ['## #####'],
  },
  {
    name: 'Cape Verde',
    cca2: 'CV',
    flag: '🇨🇻',
    code: '+238',
    phoneMasks: ['### ## ##'],
  },
  {
    name: 'Costa Rica',
    cca2: 'CR',
    flag: '🇨🇷',
    code: '+506',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Cuba',
    cca2: 'CU',
    flag: '🇨🇺',
    code: '+53',
    phoneMasks: ['# ### ####'],
  },
  {
    name: 'Cyprus',
    cca2: 'CY',
    flag: '🇨🇾',
    code: '+357',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Czechia',
    cca2: 'CZ',
    flag: '🇨🇿',
    code: '+420',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Germany',
    cca2: 'DE',
    flag: '🇩🇪',
    code: '+49',
    phoneMasks: [
      '### ###',
      '### ## ##',
      '### ## ###',
      '### ## ####',
      '### ### ####',
      '#### ### ####',
    ],
  },
  {
    name: 'Djibouti',
    cca2: 'DJ',
    flag: '🇩🇯',
    code: '+253',
    phoneMasks: ['## ## ## ##'],
  },
  {
    name: 'Dominica',
    cca2: 'DM',
    flag: '🇩🇲',
    code: '+1',
    phoneMasks: ['767 ### ####'],
  },
  {
    name: 'Denmark',
    cca2: 'DK',
    flag: '🇩🇰',
    code: '+45',
    phoneMasks: ['## ## ## ##'],
  },
  {
    name: 'Dominican Republic',
    cca2: 'DO',
    flag: '🇩🇴',
    code: '+1',
    phoneMasks: ['809 ### ####'],
  },
  {
    name: 'Algeria',
    cca2: 'DZ',
    flag: '🇩🇿',
    code: '+213',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Ecuador',
    cca2: 'EC',
    flag: '🇪🇨',
    code: '+593',
    phoneMasks: ['# ### ####', '## ### ####'],
  },
  {
    name: 'Egypt',
    cca2: 'EG',
    flag: '🇪🇬',
    code: '+20',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Eritrea',
    cca2: 'ER',
    flag: '🇪🇷',
    code: '+291',
    phoneMasks: ['# ### ###'],
  },
  {
    name: 'Spain',
    cca2: 'ES',
    flag: '🇪🇸',
    code: '+34',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Estonia',
    cca2: 'EE',
    flag: '🇪🇪',
    code: '+372',
    phoneMasks: ['#### ####', '### ####'],
  },
  {
    name: 'Ethiopia',
    cca2: 'ET',
    flag: '🇪🇹',
    code: '+251',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Finland',
    cca2: 'FI',
    flag: '🇫🇮',
    code: '+358',
    phoneMasks: ['### ### ## ##'],
  },
  {
    name: 'Fiji',
    cca2: 'FJ',
    flag: '🇫🇯',
    code: '+679',
    phoneMasks: ['## #####'],
  },
  {
    name: 'France',
    cca2: 'FR',
    flag: '🇫🇷',
    code: '+33',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Micronesia',
    cca2: 'FM',
    flag: '🇫🇲',
    code: '+691',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Gabon',
    cca2: 'GA',
    flag: '🇬🇦',
    code: '+241',
    phoneMasks: ['# ## ## ##'],
  },
  {
    name: 'United Kingdom',
    cca2: 'GB',
    flag: '🇬🇧',
    code: '+44',
    phoneMasks: ['## #### ####'],
  },
  {
    name: 'Georgia',
    cca2: 'GE',
    flag: '🇬🇪',
    code: '+995',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Ghana',
    cca2: 'GH',
    flag: '🇬🇭',
    code: '+233',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Guinea',
    cca2: 'GN',
    flag: '🇬🇳',
    code: '+224',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Gambia',
    cca2: 'GM',
    flag: '🇬🇲',
    code: '+220',
    phoneMasks: ['### ## ##'],
  },
  {
    name: 'Guinea-Bissau',
    cca2: 'GW',
    flag: '🇬🇼',
    code: '+245',
    phoneMasks: ['# ######'],
  },
  {
    name: 'Equatorial Guinea',
    cca2: 'GQ',
    flag: '🇬🇶',
    code: '+240',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Greece',
    cca2: 'GR',
    flag: '🇬🇷',
    code: '+30',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Grenada',
    cca2: 'GD',
    flag: '🇬🇩',
    code: '+1',
    phoneMasks: ['473 ### ####'],
  },
  {
    name: 'Guatemala',
    cca2: 'GT',
    flag: '🇬🇹',
    code: '+502',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Guyana',
    cca2: 'GY',
    flag: '🇬🇾',
    code: '+592',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Honduras',
    cca2: 'HN',
    flag: '🇭🇳',
    code: '+504',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Croatia',
    cca2: 'HR',
    flag: '🇭🇷',
    code: '+385',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Haiti',
    cca2: 'HT',
    flag: '🇭🇹',
    code: '+509',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Hungary',
    cca2: 'HU',
    flag: '🇭🇺',
    code: '+36',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Indonesia',
    cca2: 'ID',
    flag: '🇮🇩',
    code: '+62',
    phoneMasks: [
      '## ### ##',
      '## ### ###',
      '## ### ####',
      '### ### ####',
      '### ### ## ###',
    ],
  },
  {
    name: 'India',
    cca2: 'IN',
    flag: '🇮🇳',
    code: '+91',
    phoneMasks: ['#### ### ###'],
  },
  {
    name: 'Ireland',
    cca2: 'IE',
    flag: '🇮🇪',
    code: '+353',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Iran',
    cca2: 'IR',
    flag: '🇮🇷',
    code: '+98',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Iraq',
    cca2: 'IQ',
    flag: '🇮🇶',
    code: '+964',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Iceland',
    cca2: 'IS',
    flag: '🇮🇸',
    code: '+354',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Israel',
    cca2: 'IL',
    flag: '🇮🇱',
    code: '+972',
    phoneMasks: ['# ### ####'],
  },
  {
    name: 'Italy',
    cca2: 'IT',
    flag: '🇮🇹',
    code: '+39',
    phoneMasks: ['# ### #####', '### #### ###'],
  },
  {
    name: 'Jamaica',
    cca2: 'JM',
    flag: '🇯🇲',
    code: '+1',
    phoneMasks: ['876 ### ####'],
  },
  {
    name: 'Jordan',
    cca2: 'JO',
    flag: '🇯🇴',
    code: '+962',
    phoneMasks: ['# #### ####'],
  },
  {
    name: 'Japan',
    cca2: 'JP',
    flag: '🇯🇵',
    code: '+81',
    phoneMasks: ['### ### ###', '## #### ####'],
  },
  {
    name: 'Kazakhstan',
    cca2: 'KZ',
    flag: '🇰🇿',
    code: '+997',
    phoneMasks: ['### ### ## ##'],
  },
  {
    name: 'Kenya',
    cca2: 'KE',
    flag: '🇰🇪',
    code: '+254',
    phoneMasks: ['### ######'],
  },
  {
    name: 'Kyrgyzstan',
    cca2: 'KG',
    flag: '🇰🇬',
    code: '+996',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Cambodia',
    cca2: 'KH',
    flag: '🇰🇭',
    code: '+855',
    phoneMasks: ['## ### ##'],
  },
  {
    name: 'Kiribati',
    cca2: 'KI',
    flag: '🇰🇮',
    code: '+686',
    phoneMasks: ['## ###'],
  },
  {
    name: 'Saint Kitts and Nevis',
    cca2: 'KN',
    flag: '🇰🇳',
    code: '+1',
    phoneMasks: ['869 ### ####'],
  },
  {
    name: 'South Korea',
    cca2: 'KR',
    flag: '🇰🇷',
    code: '+82',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Kuwait',
    cca2: 'KW',
    flag: '🇰🇼',
    code: '+965',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Laos',
    cca2: 'LA',
    flag: '🇱🇦',
    code: '+856',
    phoneMasks: ['## ### ###', '#### ### ###'],
  },
  {
    name: 'Lebanon',
    cca2: 'LB',
    flag: '🇱🇧',
    code: '+961',
    phoneMasks: ['## ### ###', '# ### ###'],
  },
  {
    name: 'Liberia',
    cca2: 'LR',
    flag: '🇱🇷',
    code: '+231',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Libya',
    cca2: 'LY',
    flag: '🇱🇾',
    code: '+218',
    phoneMasks: ['## ### ###', '## ### ####'],
  },
  {
    name: 'Saint Lucia',
    cca2: 'LC',
    flag: '🇱🇨',
    code: '+1',
    phoneMasks: ['758 ### ####'],
  },
  {
    name: 'Liechtenstein',
    cca2: 'LI',
    flag: '🇱🇮',
    code: '+423',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Sri Lanka',
    cca2: 'LK',
    flag: '🇱🇰',
    code: '+94',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Lesotho',
    cca2: 'LS',
    flag: '🇱🇸',
    code: '+266',
    phoneMasks: ['# ### ####'],
  },
  {
    name: 'Lithuania',
    cca2: 'LT',
    flag: '🇱🇹',
    code: '+370',
    phoneMasks: ['### ## ###'],
  },
  {
    name: 'Luxembourg',
    cca2: 'LU',
    flag: '🇱🇺',
    code: '+352',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Latvia',
    cca2: 'LV',
    flag: '🇱🇻',
    code: '+371',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Morocco',
    cca2: 'MA',
    flag: '🇲🇦',
    code: '+212',
    phoneMasks: ['## #### ###'],
  },
  {
    name: 'Monaco',
    cca2: 'MC',
    flag: '🇲🇨',
    code: '+377',
    phoneMasks: ['## ### ###', '### ### ###'],
  },
  {
    name: 'Moldova',
    cca2: 'MD',
    flag: '🇲🇩',
    code: '+373',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Madagascar',
    cca2: 'MG',
    flag: '🇲🇬',
    code: '+261',
    phoneMasks: ['## ## #####'],
  },
  {
    name: 'Maldives',
    cca2: 'MV',
    flag: '🇲🇻',
    code: '+960',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Mexico',
    cca2: 'MX',
    flag: '🇲🇽',
    code: '+52',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Marshall Islands',
    cca2: 'MH',
    flag: '🇲🇭',
    code: '+692',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Macedonia',
    cca2: 'MK',
    flag: '🇲🇰',
    code: '+389',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Mali',
    cca2: 'ML',
    flag: '🇲🇱',
    code: '+223',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Malta',
    cca2: 'MT',
    flag: '🇲🇹',
    code: '+356',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Myanmar',
    cca2: 'MM',
    flag: '🇲🇲',
    code: '+95',
    phoneMasks: ['### ###', '# ### ###', '## ### ###'],
  },
  {
    name: 'Montenegro',
    cca2: 'ME',
    flag: '🇲🇪',
    code: '+382',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Mongolia',
    cca2: 'MN',
    flag: '🇲🇳',
    code: '+976',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Mozambique',
    cca2: 'MZ',
    flag: '🇲🇿',
    code: '+258',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Mauritania',
    cca2: 'MR',
    flag: '🇲🇷',
    code: '+222',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Mauritius',
    cca2: 'MU',
    flag: '🇲🇺',
    code: '+230',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Malawi',
    cca2: 'MW',
    flag: '🇲🇼',
    code: '+265',
    phoneMasks: ['# ### ###', '# #### ####'],
  },
  {
    name: 'Malaysia',
    cca2: 'MY',
    flag: '🇲🇾',
    code: '+60',
    phoneMasks: ['# ### ###', '## ### ###', '## ### ####'],
  },
  {
    name: 'Namibia',
    cca2: 'NA',
    flag: '🇳🇦',
    code: '+264',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Niger',
    cca2: 'NE',
    flag: '🇳🇪',
    code: '+227',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Nigeria',
    cca2: 'NG',
    flag: '🇳🇬',
    code: '+234',
    phoneMasks: ['## ### ##', '## ### ###', '### ### ####'],
  },
  {
    name: 'Nicaragua',
    cca2: 'NI',
    flag: '🇳🇮',
    code: '+505',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Netherlands',
    cca2: 'NL',
    flag: '🇳🇱',
    code: '+31',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Norway',
    cca2: 'NO',
    flag: '🇳🇴',
    code: '+47',
    phoneMasks: ['### ## ###'],
  },
  {
    name: 'Nepal',
    cca2: 'NP',
    flag: '🇳🇵',
    code: '+977',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Nauru',
    cca2: 'NR',
    flag: '🇳🇷',
    code: '+674',
    phoneMasks: ['### ####'],
  },
  {
    name: 'New Zealand',
    cca2: 'NZ',
    flag: '🇳🇿',
    code: '+64',
    phoneMasks: ['## ### ###', '### ### ###', '### ### ####'],
  },
  {
    name: 'Oman',
    cca2: 'OM',
    flag: '🇴🇲',
    code: '+968',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Pakistan',
    cca2: 'PK',
    flag: '🇵🇰',
    code: '+92',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Panama',
    cca2: 'PA',
    flag: '🇵🇦',
    code: '+507',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Peru',
    cca2: 'PE',
    flag: '🇵🇪',
    code: '+51',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Philippines',
    cca2: 'PH',
    flag: '🇵🇭',
    code: '+63',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Palau',
    cca2: 'PW',
    flag: '🇵🇼',
    code: '+680',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Papua New Guinea',
    cca2: 'PG',
    flag: '🇵🇬',
    code: '+675',
    phoneMasks: ['### ## ###'],
  },
  {
    name: 'Poland',
    cca2: 'PL',
    flag: '🇵🇱',
    code: '+48',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'North Korea',
    cca2: 'KP',
    flag: '🇰🇵',
    code: '+850',
    phoneMasks: [
      '### ###',
      '#### ####',
      '## ### ###',
      '### #### ###',
      '#### #############',
    ],
  },
  {
    name: 'Portugal',
    cca2: 'PT',
    flag: '🇵🇹',
    code: '+351',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Paraguay',
    cca2: 'PY',
    flag: '🇵🇾',
    code: '+595',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Qatar',
    cca2: 'QA',
    flag: '🇶🇦',
    code: '+974',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Romania',
    cca2: 'RO',
    flag: '🇷🇴',
    code: '+40',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Russia',
    cca2: 'RU',
    flag: '🇷🇺',
    code: '+7',
    phoneMasks: ['### ### ## ##'],
  },
  {
    name: 'Rwanda',
    cca2: 'RW',
    flag: '🇷🇼',
    code: '+250',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Saudi Arabia',
    cca2: 'SA',
    flag: '🇸🇦',
    code: '+966',
    phoneMasks: ['# ### ####', '# #### ####'],
  },
  {
    name: 'Sudan',
    cca2: 'SD',
    flag: '🇸🇩',
    code: '+249',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Senegal',
    cca2: 'SN',
    flag: '🇸🇳',
    code: '+221',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Singapore',
    cca2: 'SG',
    flag: '🇸🇬',
    code: '+65',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Solomon Islands',
    cca2: 'SB',
    flag: '🇸🇧',
    code: '+677',
    phoneMasks: ['#####', '### ####'],
  },
  {
    name: 'Sierra Leone',
    cca2: 'SL',
    flag: '🇸🇱',
    code: '+232',
    phoneMasks: ['## ######'],
  },
  {
    name: 'El Salvador',
    cca2: 'SV',
    flag: '🇸🇻',
    code: '+503',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'San Marino',
    cca2: 'SM',
    flag: '🇸🇲',
    code: '+378',
    phoneMasks: ['#### ######'],
  },
  {
    name: 'Somalia',
    cca2: 'SO',
    flag: '🇸🇴',
    code: '+252',
    phoneMasks: ['## ### ###', '# ### ###'],
  },
  {
    name: 'Serbia',
    cca2: 'RS',
    flag: '🇷🇸',
    code: '+381',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'South Sudan',
    cca2: 'SS',
    flag: '🇸🇸',
    code: '+211',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'São Tomé and Príncipe',
    cca2: 'ST',
    flag: '🇸🇹',
    code: '+239',
    phoneMasks: ['## #####'],
  },
  {
    name: 'Suriname',
    cca2: 'SR',
    flag: '🇸🇷',
    code: '+597',
    phoneMasks: ['### ###', '### ####'],
  },
  {
    name: 'Slovakia',
    cca2: 'SK',
    flag: '🇸🇰',
    code: '+421',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Slovenia',
    cca2: 'SI',
    flag: '🇸🇮',
    code: '+386',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Sweden',
    cca2: 'SE',
    flag: '🇸🇪',
    code: '+46',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Swaziland',
    cca2: 'SZ',
    flag: '🇸🇿',
    code: '+268',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Seychelles',
    cca2: 'SC',
    flag: '🇸🇨',
    code: '+248',
    phoneMasks: ['# ### ###'],
  },
  {
    name: 'Syria',
    cca2: 'SY',
    flag: '🇸🇾',
    code: '+963',
    phoneMasks: ['## #### ###'],
  },
  {
    name: 'Chad',
    cca2: 'TD',
    flag: '🇹🇩',
    code: '+235',
    phoneMasks: ['## ## ## ##'],
  },
  {
    name: 'Togo',
    cca2: 'TG',
    flag: '🇹🇬',
    code: '+228',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Thailand',
    cca2: 'TH',
    flag: '🇹🇭',
    code: '+66',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Tajikistan',
    cca2: 'TJ',
    flag: '🇹🇯',
    code: '+992',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Turkmenistan',
    cca2: 'TM',
    flag: '🇹🇲',
    code: '+993',
    phoneMasks: ['# ### ####'],
  },
  {
    name: 'Timor-Leste',
    cca2: 'TL',
    flag: '🇹🇱',
    code: '+670',
    phoneMasks: ['### ####', '### #####'],
  },
  {
    name: 'Tonga',
    cca2: 'TO',
    flag: '🇹🇴',
    code: '+676',
    phoneMasks: ['#####'],
  },
  {
    name: 'Trinidad and Tobago',
    cca2: 'TT',
    flag: '🇹🇹',
    code: '+1',
    phoneMasks: ['868 ### ####'],
  },
  {
    name: 'Tunisia',
    cca2: 'TN',
    flag: '🇹🇳',
    code: '+216',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Turkey',
    cca2: 'TR',
    flag: '🇹🇷',
    code: '+90',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Tuvalu',
    cca2: 'TV',
    flag: '🇹🇻',
    code: '+688',
    phoneMasks: ['#####', '######'],
  },
  {
    name: 'Tanzania',
    cca2: 'TZ',
    flag: '🇹🇿',
    code: '+255',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Uganda',
    cca2: 'UG',
    flag: '🇺🇬',
    code: '+256',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Ukraine',
    cca2: 'UA',
    flag: '🇺🇦',
    code: '+380',
    phoneMasks: ['## ### ## ##'],
  },
  {
    name: 'Uruguay',
    cca2: 'UY',
    flag: '🇺🇾',
    code: '+598',
    phoneMasks: ['# ### ## ##'],
  },
  {
    name: 'United States',
    cca2: 'US',
    flag: '🇺🇸',
    code: '+1',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Uzbekistan',
    cca2: 'UZ',
    flag: '🇺🇿',
    code: '+998',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Vatican City',
    cca2: 'VA',
    flag: '🇻🇦',
    code: '+39',
    phoneMasks: ['06 698#####'],
  },
  {
    name: 'Saint Vincent and the Grenadines',
    cca2: 'VC',
    flag: '🇻🇨',
    code: '+1',
    phoneMasks: ['784 ### ####'],
  },
  {
    name: 'Venezuela',
    cca2: 'VE',
    flag: '🇻🇪',
    code: '+58',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Vietnam',
    cca2: 'VN',
    flag: '🇻🇳',
    code: '+84',
    phoneMasks: ['### #### ###'],
  },
  {
    name: 'Vanuatu',
    cca2: 'VU',
    flag: '🇻🇺',
    code: '+678',
    phoneMasks: ['#####', '## #####'],
  },
  {
    name: 'Samoa',
    cca2: 'WS',
    flag: '🇼🇸',
    code: '+685',
    phoneMasks: ['## ####'],
  },
  {
    name: 'Yemen',
    cca2: 'YE',
    flag: '🇾🇪',
    code: '+967',
    phoneMasks: ['# ### ###', '## ### ###', '### ### ###'],
  },
  {
    name: 'South Africa',
    cca2: 'ZA',
    flag: '🇿🇦',
    code: '+27',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Zambia',
    cca2: 'ZM',
    flag: '🇿🇲',
    code: '+260',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Zimbabwe',
    cca2: 'ZW',
    flag: '🇿🇼',
    code: '+263',
    phoneMasks: ['# ######'],
  },
];
