export const countriesPhoneCodeList = [
  {code: '+247', matrix: '####'},
  {code: '+290', matrix: '####'},
  {code: '+683', matrix: '####'},
  {code: '+690', matrix: '####'},
  {code: '+500', matrix: '#####'},
  {code: '+676', matrix: '#####'},
  {code: '+677', matrix: '#####'},
  {code: '+678', matrix: '#####'},
  {code: '+688', matrix: '#####'},
  {code: '+49', matrix: '### ###'},
  {code: '+682', matrix: '## ###'},
  {code: '+686', matrix: '## ###'},
  {code: '+688', matrix: '######'},
  {code: '+95', matrix: '### ###'},
  {code: '+298', matrix: '### ###'},
  {code: '+376', matrix: '### ###'},
  {code: '+387', matrix: '## ####'},
  {code: '+508', matrix: '## ####'},
  {code: '+597', matrix: '### ###'},
  {code: '+672', matrix: '### ###'},
  {code: '+681', matrix: '## ####'},
  {code: '+685', matrix: '## ####'},
  {code: '+687', matrix: '## ####'},
  {code: '+850', matrix: '### ###'},
  {code: '+230', matrix: '### ####'},
  {code: '+239', matrix: '## #####'},
  {code: '+245', matrix: '# ######'},
  {code: '+246', matrix: '### ####'},
  {code: '+263', matrix: '# ######'},
  {code: '+269', matrix: '## #####'},
  {code: '+297', matrix: '### ####'},
  {code: '+299', matrix: '## ## ##'},
  {code: '+354', matrix: '### ####'},
  {code: '+372', matrix: '### ####'},
  {code: '+387', matrix: '## #####'},
  {code: '+49', matrix: '### ## ##'},
  {code: '+501', matrix: '### ####'},
  {code: '+507', matrix: '### ####'},
  {code: '+592', matrix: '### ####'},
  {code: '+597', matrix: '### ####'},
  {code: '+599', matrix: '### ####'},
  {code: '+60', matrix: '# ### ###'},
  {code: '+62', matrix: '## ### ##'},
  {code: '+65', matrix: '#### ####'},
  {code: '+670', matrix: '### ####'},
  {code: '+673', matrix: '### ####'},
  {code: '+674', matrix: '### ####'},
  {code: '+677', matrix: '### ####'},
  {code: '+678', matrix: '## #####'},
  {code: '+679', matrix: '## #####'},
  {code: '+680', matrix: '### ####'},
  {code: '+689', matrix: '## ## ##'},
  {code: '+691', matrix: '### ####'},
  {code: '+692', matrix: '### ####'},
  {code: '+95', matrix: '# ### ###'},
  {code: '+960', matrix: '### ####'},
  {code: '+220', matrix: '### ## ##'},
  {code: '+232', matrix: '## ######'},
  {code: '+234', matrix: '## ### ##'},
  {code: '+237', matrix: '#### ####'},
  {code: '+238', matrix: '### ## ##'},
  {code: '+248', matrix: '# ### ###'},
  {code: '+252', matrix: '# ### ###'},
  {code: '+265', matrix: '# ### ###'},
  {code: '+291', matrix: '# ### ###'},
  {code: '+350', matrix: '### #####'},
  {code: '+356', matrix: '#### ####'},
  {code: '+372', matrix: '#### ####'},
  {code: '+373', matrix: '#### ####'},
  {code: '+47', matrix: '### ## ###'},
  {code: '+49', matrix: '### ## ###'},
  {code: '+504', matrix: '#### ####'},
  {code: '+505', matrix: '#### ####'},
  {code: '+506', matrix: '#### ####'},
  {code: '+52', matrix: '## ## ####'},
  {code: '+53', matrix: '# ### ####'},
  {code: '+599', matrix: '#### ####'},
  {code: '+60', matrix: '## ### ###'},
  {code: '+62', matrix: '## ### ###'},
  {code: '+64', matrix: '## ### ###'},
  {code: '+66', matrix: '## ### ###'},
  {code: '+670', matrix: '### #####'},
  {code: '+850', matrix: '#### ####'},
  {code: '+852', matrix: '#### ####'},
  {code: '+853', matrix: '#### ####'},
  {code: '+886', matrix: '#### ####'},
  {code: '+95', matrix: '## ### ###'},
  {code: '+961', matrix: '# ### ###'},
  {code: '+965', matrix: '#### ####'},
  {code: '+967', matrix: '# ### ###'},
  {code: '+973', matrix: '#### ####'},
  {code: '+974', matrix: '#### ####'},
  {code: '+975', matrix: '# ### ###'},
  {code: '+1', matrix: '### ### ####'},
  {code: '+216', matrix: '## ### ###'},
  {code: '+218', matrix: '## ### ###'},
  {code: '+222', matrix: '## ## ####'},
  {code: '+223', matrix: '## ## ####'},
  {code: '+224', matrix: '## ### ###'},
  {code: '+225', matrix: '## ### ###'},
  {code: '+226', matrix: '## ## ####'},
  {code: '+227', matrix: '## ## ####'},
  {code: '+228', matrix: '## ### ###'},
  {code: '+229', matrix: '## ## ####'},
  {code: '+231', matrix: '## ### ###'},
  {code: '+234', matrix: '## ### ###'},
  {code: '+236', matrix: '## ## ####'},
  {code: '+241', matrix: '# ## ## ##'},
  {code: '+252', matrix: '## ### ###'},
  {code: '+254', matrix: '### ######'},
  {code: '+257', matrix: '## ## ####'},
  {code: '+258', matrix: '## ### ###'},
  {code: '+262', matrix: '##### ####'},
  {code: '+262', matrix: '##### ####'},
  {code: '+266', matrix: '# ### ####'},
  {code: '+267', matrix: '## ### ###'},
  {code: '+268', matrix: '## ## ####'},
  {code: '+27', matrix: '## ### ####'},
  {code: '+31', matrix: '## ### ####'},
  {code: '+32', matrix: '### ### ###'},
  {code: '+33', matrix: '### ### ###'},
  {code: '+34', matrix: '### ### ###'},
  {code: '+357', matrix: '## ### ###'},
  {code: '+36', matrix: '### ### ###'},
  {code: '+370', matrix: '### ## ###'},
  {code: '+371', matrix: '## ### ###'},
  {code: '+374', matrix: '## ### ###'},
  {code: '+377', matrix: '## ### ###'},
  {code: '+382', matrix: '## ### ###'},
  {code: '+385', matrix: '## ### ###'},
  {code: '+386', matrix: '## ### ###'},
  {code: '+389', matrix: '## ### ###'},
  {code: '+39', matrix: '# ### #####'},
  {code: '+40', matrix: '## ### ####'},
  {code: '+41', matrix: '## ### ####'},
  {code: '+45', matrix: '## ## ## ##'},
  {code: '+46', matrix: '## ### ####'},
  {code: '+48', matrix: '### ### ###'},
  {code: '+49', matrix: '### ## ####'},
  {code: '+502', matrix: '# ### ####'},
  {code: '+503', matrix: '## ## ####'},
  {code: '+509', matrix: '## ## ####'},
  {code: '+51', matrix: '### ### ###'},
  {code: '+56', matrix: '# #### ####'},
  {code: '+591', matrix: '# ### ####'},
  {code: '+593', matrix: '# ### ####'},
  {code: '+594', matrix: '##### ####'},
  {code: '+60', matrix: '## ### ####'},
  {code: '+60', matrix: '### ### ###'},
  {code: '+61', matrix: '# #### ####'},
  {code: '+62', matrix: '## ### ####'},
  {code: '+64', matrix: '### ### ###'},
  {code: '+66', matrix: '## ### ####'},
  {code: '+675', matrix: '### ## ###'},
  {code: '+81', matrix: '### ### ###'},
  {code: '+82', matrix: '## ### ####'},
  {code: '+84', matrix: '## #### ###'},
  {code: '+850', matrix: '## ### ###'},
  {code: '+855', matrix: '## ### ###'},
  {code: '+856', matrix: '## ### ###'},
  {code: '+880', matrix: '## ### ###'},
  {code: '+93', matrix: '## ### ####'},
  {code: '+94', matrix: '## ### ####'},
  {code: '+961', matrix: '## ### ###'},
  {code: '+966', matrix: '# ### ####'},
  {code: '+967', matrix: '## ### ###'},
  {code: '+968', matrix: '## ### ###'},
  {code: '+971', matrix: '# ### ####'},
  {code: '+972', matrix: '# ### ####'},
  {code: '+975', matrix: '## ### ###'},
  {code: '+976', matrix: '## ## ####'},
  {code: '+977', matrix: '## ### ###'},
  {code: '+993', matrix: '# ### ####'},
  {code: '+20', matrix: '### ### ####'},
  {code: '+211', matrix: '## ### ####'},
  {code: '+212', matrix: '## #### ###'},
  {code: '+213', matrix: '## ### ####'},
  {code: '+218', matrix: '## ### ####'},
  {code: '+221', matrix: '## ### ####'},
  {code: '+233', matrix: '### ### ###'},
  {code: '+235', matrix: '## ## ## ##'},
  {code: '+240', matrix: '## ### ####'},
  {code: '+242', matrix: '## ### ####'},
  {code: '+243', matrix: '### ### ###'},
  {code: '+244', matrix: '### ### ###'},
  {code: '+249', matrix: '## ### ####'},
  {code: '+250', matrix: '### ### ###'},
  {code: '+251', matrix: '## ### ####'},
  {code: '+253', matrix: '## ## ## ##'},
  {code: '+255', matrix: '## ### ####'},
  {code: '+256', matrix: '### ### ###'},
  {code: '+260', matrix: '## ### ####'},
  {code: '+261', matrix: '## ## #####'},
  {code: '+264', matrix: '## ### ####'},
  {code: '+265', matrix: '# #### ####'},
  {code: '+30', matrix: '### ### ####'},
  {code: '+351', matrix: '### ### ###'},
  {code: '+352', matrix: '### ### ###'},
  {code: '+353', matrix: '### ### ###'},
  {code: '+355', matrix: '### ### ###'},
  {code: '+359', matrix: '### ### ###'},
  {code: '+377', matrix: '### ### ###'},
  {code: '+378', matrix: '#### ######'},
  {code: '+381', matrix: '## ### ####'},
  {code: '+39', matrix: '### #### ###'},
  {code: '+420', matrix: '### ### ###'},
  {code: '+421', matrix: '### ### ###'},
  {code: '+43', matrix: '### ### ####'},
  {code: '+44', matrix: '## #### ####'},
  {code: '+49', matrix: '### ### ####'},
  {code: '+52', matrix: '### ### ####'},
  {code: '+54', matrix: '### ### ####'},
  {code: '+57', matrix: '### ### ####'},
  {code: '+58', matrix: '### ### ####'},
  {code: '+590', matrix: '### ### ###'},
  {code: '+593', matrix: '## ### ####'},
  {code: '+595', matrix: '### ### ###'},
  {code: '+598', matrix: '# ### ## ##'},
  {code: '+62', matrix: '### ### ####'},
  {code: '+63', matrix: '### ### ####'},
  {code: '+64', matrix: '### ### ####'},
  {code: '+7', matrix: '### ### ## ##'},
  {code: '+81', matrix: '## #### ####'},
  {code: '+84', matrix: '### #### ###'},
  {code: '+86', matrix: '### #### ###'},
  {code: '+886', matrix: '# #### ####'},
  {code: '+90', matrix: '### ### ####'},
  {code: '+91', matrix: '#### ### ###'},
  {code: '+92', matrix: '### ### ####'},
  {code: '+962', matrix: '# #### ####'},
  {code: '+963', matrix: '## #### ###'},
  {code: '+966', matrix: '# #### ####'},
  {code: '+967', matrix: '### ### ###'},
  {code: '+970', matrix: '## ### ####'},
  {code: '+971', matrix: '## ### ####'},
  {code: '+972', matrix: '## ### ####'},
  {code: '+98', matrix: '### ### ####'},
  {code: '+992', matrix: '## ### ####'},
  {code: '+995', matrix: '### ### ###'},
  {code: '+996', matrix: '### ### ###'},
  {code: '+998', matrix: '## ### ####'},
  {code: '+234', matrix: '### ### ####'},
  {code: '+234', matrix: '### ### ####'},
  {code: '+375', matrix: '## ### ## ##'},
  {code: '+380', matrix: '## ### ## ##'},
  {code: '+423', matrix: '### ### ####'},
  {code: '+49', matrix: '#### ### ####'},
  {code: '+55', matrix: '## ##### ####'},
  {code: '+596', matrix: '### ## ## ##'},
  {code: '+850', matrix: '### #### ###'},
  {code: '+856', matrix: '#### ### ###'},
  {code: '+86', matrix: '### #### ####'},
  {code: '+964', matrix: '### ### ####'},
  {code: '+994', matrix: '## ### ## ##'},
  {code: '+358', matrix: '### ### ## ##'},
  {code: '+62', matrix: '### ### ## ###'},
  {code: '+86', matrix: '## ##### #####'},
  {code: '+850', matrix: '#### #############'},
];
