export const countries = [
  {
    name: 'Afghanistan',
    cca2: 'AF',
    flag: '🇦🇫',
    callingCode: '+93',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Angola',
    cca2: 'AO',
    flag: '🇦🇴',
    callingCode: '+244',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Albania',
    cca2: 'AL',
    flag: '🇦🇱',
    callingCode: '+355',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Andorra',
    cca2: 'AD',
    flag: '🇦🇩',
    callingCode: '+376',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'United Arab Emirates',
    cca2: 'AE',
    flag: '🇦🇪',
    callingCode: '+971',
    phoneMasks: ['# ### ####', '## ### ####'],
  },
  {
    name: 'Argentina',
    cca2: 'AR',
    flag: '🇦🇷',
    callingCode: '+54',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Armenia',
    cca2: 'AM',
    flag: '🇦🇲',
    callingCode: '+374',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Antigua and Barbuda',
    cca2: 'AG',
    flag: '🇦🇬',
    callingCode: '+1',
    phoneMasks: ['268 ### ####'],
  },
  {
    name: 'Australia',
    cca2: 'AU',
    flag: '🇦🇺',
    callingCode: '+61',
    phoneMasks: ['# #### ####'],
  },
  {
    name: 'Austria',
    cca2: 'AT',
    flag: '🇦🇹',
    callingCode: '+43',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Azerbaijan',
    cca2: 'AZ',
    flag: '🇦🇿',
    callingCode: '+994',
    phoneMasks: ['## ### ## ##'],
  },
  {
    name: 'Burundi',
    cca2: 'BI',
    flag: '🇧🇮',
    callingCode: '+257',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Belgium',
    cca2: 'BE',
    flag: '🇧🇪',
    callingCode: '+32',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Benin',
    cca2: 'BJ',
    flag: '🇧🇯',
    callingCode: '+229',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Bermuda',
    cca2: 'BM',
    flag: '🇧🇲',
    callingCode: '+1',
    phoneMasks: ['441 ### ####'],
  },
  {
    name: 'Burkina Faso',
    cca2: 'BF',
    flag: '🇧🇫',
    callingCode: '+226',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Bangladesh',
    cca2: 'BD',
    flag: '🇧🇩',
    callingCode: '+880',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Bulgaria',
    cca2: 'BG',
    flag: '🇧🇬',
    callingCode: '+359',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Bahrain',
    cca2: 'BH',
    flag: '🇧🇭',
    callingCode: '+973',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Bahamas',
    cca2: 'BS',
    flag: '🇧🇸',
    callingCode: '+1',
    phoneMasks: ['242 ### ####'],
  },
  {
    name: 'Bosnia and Herzegovina',
    cca2: 'BA',
    flag: '🇧🇦',
    callingCode: '+387',
    phoneMasks: ['## ####', '## #####'],
  },
  {
    name: 'Belarus',
    cca2: 'BY',
    flag: '🇧🇾',
    callingCode: '+375',
    phoneMasks: ['## ### ## ##'],
  },
  {
    name: 'Belize',
    cca2: 'BZ',
    flag: '🇧🇿',
    callingCode: '+501',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Bolivia',
    cca2: 'BO',
    flag: '🇧🇴',
    callingCode: '+591',
    phoneMasks: ['# ### ####'],
  },
  {
    name: 'Brazil',
    cca2: 'BR',
    flag: '🇧🇷',
    callingCode: '+55',
    phoneMasks: ['## ##### ####'],
  },
  {
    name: 'Barbados',
    cca2: 'BB',
    flag: '🇧🇧',
    callingCode: '+1',
    phoneMasks: ['246 ### ####'],
  },
  {
    name: 'Brunei',
    cca2: 'BN',
    flag: '🇧🇳',
    callingCode: '+673',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Bhutan',
    cca2: 'BT',
    flag: '🇧🇹',
    callingCode: '+975',
    phoneMasks: ['# ### ###'],
  },
  {
    name: 'Botswana',
    cca2: 'BW',
    flag: '🇧🇼',
    callingCode: '+267',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Central African Republic',
    cca2: 'CF',
    flag: '🇨🇫',
    callingCode: '+236',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Canada',
    cca2: 'CA',
    flag: '🇨🇦',
    callingCode: '+1',
    phoneMasks: [
      '204 ### ####',
      '226 ### ####',
      '236 ### ####',
      '249 ### ####',
      '250 ### ####',
      '263 ### ####',
      '289 ### ####',
      '306 ### ####',
      '343 ### ####',
      '354 ### ####',
      '365 ### ####',
      '367 ### ####',
      '368 ### ####',
      '403 ### ####',
      '416 ### ####',
      '418 ### ####',
      '431 ### ####',
      '437 ### ####',
      '438 ### ####',
      '450 ### ####',
      '468 ### ####',
      '474 ### ####',
      '506 ### ####',
      '514 ### ####',
      '519 ### ####',
      '548 ### ####',
      '579 ### ####',
      '581 ### ####',
      '584 ### ####',
      '587 ### ####',
      '604 ### ####',
      '613 ### ####',
      '639 ### ####',
      '647 ### ####',
      '672 ### ####',
      '683 ### ####',
      '705 ### ####',
      '709 ### ####',
      '742 ### ####',
      '753 ### ####',
      '778 ### ####',
      '780 ### ####',
      '782 ### ####',
      '807 ### ####',
      '819 ### ####',
      '825 ### ####',
      '867 ### ####',
      '873 ### ####',
      '902 ### ####',
      '905 ### ####',
    ],
  },
  {
    name: 'Switzerland',
    cca2: 'CH',
    flag: '🇨🇭',
    callingCode: '+41',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Chile',
    cca2: 'CL',
    flag: '🇨🇱',
    callingCode: '+56',
    phoneMasks: ['# #### ####'],
  },
  {
    name: 'China',
    cca2: 'CN',
    flag: '🇨🇳',
    callingCode: '+86',
    phoneMasks: ['### #### ###', '### #### ####', '## ##### #####'],
  },
  {
    name: 'Ivory Coast',
    cca2: 'CI',
    flag: '🇨🇮',
    callingCode: '+225',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Cameroon',
    cca2: 'CM',
    flag: '🇨🇲',
    callingCode: '+237',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'DR Congo',
    cca2: 'CD',
    flag: '🇨🇩',
    callingCode: '+243',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Republic of the Congo',
    cca2: 'CG',
    flag: '🇨🇬',
    callingCode: '+242',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Colombia',
    cca2: 'CO',
    flag: '🇨🇴',
    callingCode: '+57',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Comoros',
    cca2: 'KM',
    flag: '🇰🇲',
    callingCode: '+269',
    phoneMasks: ['## #####'],
  },
  {
    name: 'Cape Verde',
    cca2: 'CV',
    flag: '🇨🇻',
    callingCode: '+238',
    phoneMasks: ['### ## ##'],
  },
  {
    name: 'Costa Rica',
    cca2: 'CR',
    flag: '🇨🇷',
    callingCode: '+506',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Cuba',
    cca2: 'CU',
    flag: '🇨🇺',
    callingCode: '+53',
    phoneMasks: ['# ### ####'],
  },
  {
    name: 'Cyprus',
    cca2: 'CY',
    flag: '🇨🇾',
    callingCode: '+357',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Czechia',
    cca2: 'CZ',
    flag: '🇨🇿',
    callingCode: '+420',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Germany',
    cca2: 'DE',
    flag: '🇩🇪',
    callingCode: '+49',
    phoneMasks: [
      '### ###',
      '### ## ##',
      '### ## ###',
      '### ## ####',
      '### ### ####',
      '#### ### ####',
    ],
  },
  {
    name: 'Djibouti',
    cca2: 'DJ',
    flag: '🇩🇯',
    callingCode: '+253',
    phoneMasks: ['## ## ## ##'],
  },
  {
    name: 'Dominica',
    cca2: 'DM',
    flag: '🇩🇲',
    callingCode: '+1',
    phoneMasks: ['767 ### ####'],
  },
  {
    name: 'Denmark',
    cca2: 'DK',
    flag: '🇩🇰',
    callingCode: '+45',
    phoneMasks: ['## ## ## ##'],
  },
  {
    name: 'Dominican Republic',
    cca2: 'DO',
    flag: '🇩🇴',
    callingCode: '+1',
    phoneMasks: ['809 ### ####'],
  },
  {
    name: 'Algeria',
    cca2: 'DZ',
    flag: '🇩🇿',
    callingCode: '+213',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Ecuador',
    cca2: 'EC',
    flag: '🇪🇨',
    callingCode: '+593',
    phoneMasks: ['# ### ####', '## ### ####'],
  },
  {
    name: 'Egypt',
    cca2: 'EG',
    flag: '🇪🇬',
    callingCode: '+20',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Eritrea',
    cca2: 'ER',
    flag: '🇪🇷',
    callingCode: '+291',
    phoneMasks: ['# ### ###'],
  },
  {
    name: 'Spain',
    cca2: 'ES',
    flag: '🇪🇸',
    callingCode: '+34',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Estonia',
    cca2: 'EE',
    flag: '🇪🇪',
    callingCode: '+372',
    phoneMasks: ['#### ####', '### ####'],
  },
  {
    name: 'Ethiopia',
    cca2: 'ET',
    flag: '🇪🇹',
    callingCode: '+251',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Finland',
    cca2: 'FI',
    flag: '🇫🇮',
    callingCode: '+358',
    phoneMasks: ['### ### ## ##'],
  },
  {
    name: 'Fiji',
    cca2: 'FJ',
    flag: '🇫🇯',
    callingCode: '+679',
    phoneMasks: ['## #####'],
  },
  {
    name: 'France',
    cca2: 'FR',
    flag: '🇫🇷',
    callingCode: '+33',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Micronesia',
    cca2: 'FM',
    flag: '🇫🇲',
    callingCode: '+691',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Gabon',
    cca2: 'GA',
    flag: '🇬🇦',
    callingCode: '+241',
    phoneMasks: ['# ## ## ##'],
  },
  {
    name: 'United Kingdom',
    cca2: 'GB',
    flag: '🇬🇧',
    callingCode: '+44',
    phoneMasks: ['## #### ####'],
  },
  {
    name: 'Georgia',
    cca2: 'GE',
    flag: '🇬🇪',
    callingCode: '+995',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Ghana',
    cca2: 'GH',
    flag: '🇬🇭',
    callingCode: '+233',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Guinea',
    cca2: 'GN',
    flag: '🇬🇳',
    callingCode: '+224',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Gambia',
    cca2: 'GM',
    flag: '🇬🇲',
    callingCode: '+220',
    phoneMasks: ['### ## ##'],
  },
  {
    name: 'Guinea-Bissau',
    cca2: 'GW',
    flag: '🇬🇼',
    callingCode: '+245',
    phoneMasks: ['# ######'],
  },
  {
    name: 'Equatorial Guinea',
    cca2: 'GQ',
    flag: '🇬🇶',
    callingCode: '+240',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Greece',
    cca2: 'GR',
    flag: '🇬🇷',
    callingCode: '+30',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Grenada',
    cca2: 'GD',
    flag: '🇬🇩',
    callingCode: '+1',
    phoneMasks: ['473 ### ####'],
  },
  {
    name: 'Guatemala',
    cca2: 'GT',
    flag: '🇬🇹',
    callingCode: '+502',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Guyana',
    cca2: 'GY',
    flag: '🇬🇾',
    callingCode: '+592',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Honduras',
    cca2: 'HN',
    flag: '🇭🇳',
    callingCode: '+504',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Croatia',
    cca2: 'HR',
    flag: '🇭🇷',
    callingCode: '+385',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Haiti',
    cca2: 'HT',
    flag: '🇭🇹',
    callingCode: '+509',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Hungary',
    cca2: 'HU',
    flag: '🇭🇺',
    callingCode: '+36',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Indonesia',
    cca2: 'ID',
    flag: '🇮🇩',
    callingCode: '+62',
    phoneMasks: [
      '## ### ##',
      '## ### ###',
      '## ### ####',
      '### ### ####',
      '### ### ## ###',
    ],
  },
  {
    name: 'India',
    cca2: 'IN',
    flag: '🇮🇳',
    callingCode: '+91',
    phoneMasks: ['#### ### ###'],
  },
  {
    name: 'Ireland',
    cca2: 'IE',
    flag: '🇮🇪',
    callingCode: '+353',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Iran',
    cca2: 'IR',
    flag: '🇮🇷',
    callingCode: '+98',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Iraq',
    cca2: 'IQ',
    flag: '🇮🇶',
    callingCode: '+964',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Iceland',
    cca2: 'IS',
    flag: '🇮🇸',
    callingCode: '+354',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Israel',
    cca2: 'IL',
    flag: '🇮🇱',
    callingCode: '+972',
    phoneMasks: ['# ### ####'],
  },
  {
    name: 'Italy',
    cca2: 'IT',
    flag: '🇮🇹',
    callingCode: '+39',
    phoneMasks: ['# ### #####', '### #### ###'],
  },
  {
    name: 'Jamaica',
    cca2: 'JM',
    flag: '🇯🇲',
    callingCode: '+1',
    phoneMasks: ['876 ### ####'],
  },
  {
    name: 'Jordan',
    cca2: 'JO',
    flag: '🇯🇴',
    callingCode: '+962',
    phoneMasks: ['# #### ####'],
  },
  {
    name: 'Japan',
    cca2: 'JP',
    flag: '🇯🇵',
    callingCode: '+81',
    phoneMasks: ['### ### ###', '## #### ####'],
  },
  {
    name: 'Kazakhstan',
    cca2: 'KZ',
    flag: '🇰🇿',
    callingCode: '+7',
    phoneMasks: ['### ### ## ##'],
  },
  {
    name: 'Kenya',
    cca2: 'KE',
    flag: '🇰🇪',
    callingCode: '+254',
    phoneMasks: ['### ######'],
  },
  {
    name: 'Kyrgyzstan',
    cca2: 'KG',
    flag: '🇰🇬',
    callingCode: '+996',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Cambodia',
    cca2: 'KH',
    flag: '🇰🇭',
    callingCode: '+855',
    phoneMasks: ['## ### ##'],
  },
  {
    name: 'Kiribati',
    cca2: 'KI',
    flag: '🇰🇮',
    callingCode: '+686',
    phoneMasks: ['## ###'],
  },
  {
    name: 'Saint Kitts and Nevis',
    cca2: 'KN',
    flag: '🇰🇳',
    callingCode: '+1',
    phoneMasks: ['869 ### ####'],
  },
  {
    name: 'South Korea',
    cca2: 'KR',
    flag: '🇰🇷',
    callingCode: '+82',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Kuwait',
    cca2: 'KW',
    flag: '🇰🇼',
    callingCode: '+965',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Laos',
    cca2: 'LA',
    flag: '🇱🇦',
    callingCode: '+856',
    phoneMasks: ['## ### ###', '#### ### ###'],
  },
  {
    name: 'Lebanon',
    cca2: 'LB',
    flag: '🇱🇧',
    callingCode: '+961',
    phoneMasks: ['## ### ###', '# ### ###'],
  },
  {
    name: 'Liberia',
    cca2: 'LR',
    flag: '🇱🇷',
    callingCode: '+231',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Libya',
    cca2: 'LY',
    flag: '🇱🇾',
    callingCode: '+218',
    phoneMasks: ['## ### ###', '## ### ####'],
  },
  {
    name: 'Saint Lucia',
    cca2: 'LC',
    flag: '🇱🇨',
    callingCode: '+1',
    phoneMasks: ['758 ### ####'],
  },
  {
    name: 'Liechtenstein',
    cca2: 'LI',
    flag: '🇱🇮',
    callingCode: '+423',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Sri Lanka',
    cca2: 'LK',
    flag: '🇱🇰',
    callingCode: '+94',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Lesotho',
    cca2: 'LS',
    flag: '🇱🇸',
    callingCode: '+266',
    phoneMasks: ['# ### ####'],
  },
  {
    name: 'Lithuania',
    cca2: 'LT',
    flag: '🇱🇹',
    callingCode: '+370',
    phoneMasks: ['### ## ###'],
  },
  {
    name: 'Luxembourg',
    cca2: 'LU',
    flag: '🇱🇺',
    callingCode: '+352',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Latvia',
    cca2: 'LV',
    flag: '🇱🇻',
    callingCode: '+371',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Morocco',
    cca2: 'MA',
    flag: '🇲🇦',
    callingCode: '+212',
    phoneMasks: ['## #### ###'],
  },
  {
    name: 'Monaco',
    cca2: 'MC',
    flag: '🇲🇨',
    callingCode: '+377',
    phoneMasks: ['## ### ###', '### ### ###'],
  },
  {
    name: 'Moldova',
    cca2: 'MD',
    flag: '🇲🇩',
    callingCode: '+373',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Madagascar',
    cca2: 'MG',
    flag: '🇲🇬',
    callingCode: '+261',
    phoneMasks: ['## ## #####'],
  },
  {
    name: 'Maldives',
    cca2: 'MV',
    flag: '🇲🇻',
    callingCode: '+960',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Mexico',
    cca2: 'MX',
    flag: '🇲🇽',
    callingCode: '+52',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Marshall Islands',
    cca2: 'MH',
    flag: '🇲🇭',
    callingCode: '+692',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Macedonia',
    cca2: 'MK',
    flag: '🇲🇰',
    callingCode: '+389',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Mali',
    cca2: 'ML',
    flag: '🇲🇱',
    callingCode: '+223',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Malta',
    cca2: 'MT',
    flag: '🇲🇹',
    callingCode: '+356',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Myanmar',
    cca2: 'MM',
    flag: '🇲🇲',
    callingCode: '+95',
    phoneMasks: ['### ###', '# ### ###', '## ### ###'],
  },
  {
    name: 'Montenegro',
    cca2: 'ME',
    flag: '🇲🇪',
    callingCode: '+382',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Montserrat',
    cca2: 'MS',
    flag: '🇲🇸',
    callingCode: '+1',
    phoneMasks: ['664 ### ####'],
  },
  {
    name: 'Mongolia',
    cca2: 'MN',
    flag: '🇲🇳',
    callingCode: '+976',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Mozambique',
    cca2: 'MZ',
    flag: '🇲🇿',
    callingCode: '+258',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Mauritania',
    cca2: 'MR',
    flag: '🇲🇷',
    callingCode: '+222',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Mauritius',
    cca2: 'MU',
    flag: '🇲🇺',
    callingCode: '+230',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Malawi',
    cca2: 'MW',
    flag: '🇲🇼',
    callingCode: '+265',
    phoneMasks: ['# ### ###', '# #### ####'],
  },
  {
    name: 'Malaysia',
    cca2: 'MY',
    flag: '🇲🇾',
    callingCode: '+60',
    phoneMasks: ['# ### ###', '## ### ###', '## ### ####'],
  },
  {
    name: 'Namibia',
    cca2: 'NA',
    flag: '🇳🇦',
    callingCode: '+264',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Niger',
    cca2: 'NE',
    flag: '🇳🇪',
    callingCode: '+227',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Nigeria',
    cca2: 'NG',
    flag: '🇳🇬',
    callingCode: '+234',
    phoneMasks: ['## ### ##', '## ### ###', '### ### ####'],
  },
  {
    name: 'Nicaragua',
    cca2: 'NI',
    flag: '🇳🇮',
    callingCode: '+505',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Netherlands',
    cca2: 'NL',
    flag: '🇳🇱',
    callingCode: '+31',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Norway',
    cca2: 'NO',
    flag: '🇳🇴',
    callingCode: '+47',
    phoneMasks: ['### ## ###'],
  },
  {
    name: 'Northern Mariana Islands',
    cca2: 'MP',
    flag: '🇲🇵',
    callingCode: '+1',
    phoneMasks: ['670 ### ####'],
  },
  {
    name: 'Nepal',
    cca2: 'NP',
    flag: '🇳🇵',
    callingCode: '+977',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Nauru',
    cca2: 'NR',
    flag: '🇳🇷',
    callingCode: '+674',
    phoneMasks: ['### ####'],
  },
  {
    name: 'New Zealand',
    cca2: 'NZ',
    flag: '🇳🇿',
    callingCode: '+64',
    phoneMasks: ['## ### ###', '### ### ###', '### ### ####'],
  },
  {
    name: 'Oman',
    cca2: 'OM',
    flag: '🇴🇲',
    callingCode: '+968',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Pakistan',
    cca2: 'PK',
    flag: '🇵🇰',
    callingCode: '+92',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Panama',
    cca2: 'PA',
    flag: '🇵🇦',
    callingCode: '+507',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Peru',
    cca2: 'PE',
    flag: '🇵🇪',
    callingCode: '+51',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Philippines',
    cca2: 'PH',
    flag: '🇵🇭',
    callingCode: '+63',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Palau',
    cca2: 'PW',
    flag: '🇵🇼',
    callingCode: '+680',
    phoneMasks: ['### ####'],
  },
  {
    name: 'Papua New Guinea',
    cca2: 'PG',
    flag: '🇵🇬',
    callingCode: '+675',
    phoneMasks: ['### ## ###'],
  },
  {
    name: 'Poland',
    cca2: 'PL',
    flag: '🇵🇱',
    callingCode: '+48',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'North Korea',
    cca2: 'KP',
    flag: '🇰🇵',
    callingCode: '+850',
    phoneMasks: [
      '### ###',
      '#### ####',
      '## ### ###',
      '### #### ###',
      '#### #############',
    ],
  },
  {
    name: 'Portugal',
    cca2: 'PT',
    flag: '🇵🇹',
    callingCode: '+351',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Paraguay',
    cca2: 'PY',
    flag: '🇵🇾',
    callingCode: '+595',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Puerto Rico',
    cca2: 'PR',
    flag: '🇵🇷',
    callingCode: '+1',
    phoneMasks: ['787 ### ####', '939 ### ####'],
  },
  {
    name: 'Qatar',
    cca2: 'QA',
    flag: '🇶🇦',
    callingCode: '+974',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Romania',
    cca2: 'RO',
    flag: '🇷🇴',
    callingCode: '+40',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Russia',
    cca2: 'RU',
    flag: '🇷🇺',
    callingCode: '+7',
    phoneMasks: ['### ### ## ##'],
  },
  {
    name: 'Rwanda',
    cca2: 'RW',
    flag: '🇷🇼',
    callingCode: '+250',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Saudi Arabia',
    cca2: 'SA',
    flag: '🇸🇦',
    callingCode: '+966',
    phoneMasks: ['# ### ####', '# #### ####'],
  },
  {
    name: 'Sudan',
    cca2: 'SD',
    flag: '🇸🇩',
    callingCode: '+249',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Senegal',
    cca2: 'SN',
    flag: '🇸🇳',
    callingCode: '+221',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Singapore',
    cca2: 'SG',
    flag: '🇸🇬',
    callingCode: '+65',
    phoneMasks: ['#### ####'],
  },
  {
    name: 'Solomon Islands',
    cca2: 'SB',
    flag: '🇸🇧',
    callingCode: '+677',
    phoneMasks: ['#####', '### ####'],
  },
  {
    name: 'Sierra Leone',
    cca2: 'SL',
    flag: '🇸🇱',
    callingCode: '+232',
    phoneMasks: ['## ######'],
  },
  {
    name: 'El Salvador',
    cca2: 'SV',
    flag: '🇸🇻',
    callingCode: '+503',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'San Marino',
    cca2: 'SM',
    flag: '🇸🇲',
    callingCode: '+378',
    phoneMasks: ['#### ######'],
  },
  {
    name: 'Somalia',
    cca2: 'SO',
    flag: '🇸🇴',
    callingCode: '+252',
    phoneMasks: ['## ### ###', '# ### ###'],
  },
  {
    name: 'Serbia',
    cca2: 'RS',
    flag: '🇷🇸',
    callingCode: '+381',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'South Sudan',
    cca2: 'SS',
    flag: '🇸🇸',
    callingCode: '+211',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'São Tomé and Príncipe',
    cca2: 'ST',
    flag: '🇸🇹',
    callingCode: '+239',
    phoneMasks: ['## #####'],
  },
  {
    name: 'Suriname',
    cca2: 'SR',
    flag: '🇸🇷',
    callingCode: '+597',
    phoneMasks: ['### ###', '### ####'],
  },
  {
    name: 'Slovakia',
    cca2: 'SK',
    flag: '🇸🇰',
    callingCode: '+421',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Slovenia',
    cca2: 'SI',
    flag: '🇸🇮',
    callingCode: '+386',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Sweden',
    cca2: 'SE',
    flag: '🇸🇪',
    callingCode: '+46',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    cca2: 'SH',
    flag: '🇸🇭',
    callingCode: '+290',
    phoneMasks: ['#####'],
  },
  {
    name: 'Swaziland',
    cca2: 'SZ',
    flag: '🇸🇿',
    callingCode: '+268',
    phoneMasks: ['## ## ####'],
  },
  {
    name: 'Seychelles',
    cca2: 'SC',
    flag: '🇸🇨',
    callingCode: '+248',
    phoneMasks: ['# ### ###'],
  },
  {
    name: 'Syria',
    cca2: 'SY',
    flag: '🇸🇾',
    callingCode: '+963',
    phoneMasks: ['## #### ###'],
  },
  {
    name: 'Turks and Caicos Islands',
    cca2: 'TC',
    flag: '🇹🇨',
    callingCode: '+1',
    phoneMasks: ['649 ### ####'],
  },
  {
    name: 'Chad',
    cca2: 'TD',
    flag: '🇹🇩',
    callingCode: '+235',
    phoneMasks: ['## ## ## ##'],
  },
  {
    name: 'Togo',
    cca2: 'TG',
    flag: '🇹🇬',
    callingCode: '+228',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Thailand',
    cca2: 'TH',
    flag: '🇹🇭',
    callingCode: '+66',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Tajikistan',
    cca2: 'TJ',
    flag: '🇹🇯',
    callingCode: '+992',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Turkmenistan',
    cca2: 'TM',
    flag: '🇹🇲',
    callingCode: '+993',
    phoneMasks: ['# ### ####'],
  },
  {
    name: 'Timor-Leste',
    cca2: 'TL',
    flag: '🇹🇱',
    callingCode: '+670',
    phoneMasks: ['### ####', '### #####'],
  },
  {
    name: 'Tonga',
    cca2: 'TO',
    flag: '🇹🇴',
    callingCode: '+676',
    phoneMasks: ['#####'],
  },
  {
    name: 'Trinidad and Tobago',
    cca2: 'TT',
    flag: '🇹🇹',
    callingCode: '+1',
    phoneMasks: ['868 ### ####'],
  },
  {
    name: 'Tunisia',
    cca2: 'TN',
    flag: '🇹🇳',
    callingCode: '+216',
    phoneMasks: ['## ### ###'],
  },
  {
    name: 'Turkey',
    cca2: 'TR',
    flag: '🇹🇷',
    callingCode: '+90',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Tuvalu',
    cca2: 'TV',
    flag: '🇹🇻',
    callingCode: '+688',
    phoneMasks: ['#####', '######'],
  },
  {
    name: 'Tanzania',
    cca2: 'TZ',
    flag: '🇹🇿',
    callingCode: '+255',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Uganda',
    cca2: 'UG',
    flag: '🇺🇬',
    callingCode: '+256',
    phoneMasks: ['### ### ###'],
  },
  {
    name: 'Ukraine',
    cca2: 'UA',
    flag: '🇺🇦',
    callingCode: '+380',
    phoneMasks: ['## ### ## ##'],
  },
  {
    name: 'Uruguay',
    cca2: 'UY',
    flag: '🇺🇾',
    callingCode: '+598',
    phoneMasks: ['# ### ## ##'],
  },
  {
    name: 'United States',
    cca2: 'US',
    flag: '🇺🇸',
    callingCode: '+1',
    phoneMasks: [
      '201 ### ####',
      '202 ### ####',
      '203 ### ####',
      '205 ### ####',
      '206 ### ####',
      '207 ### ####',
      '208 ### ####',
      '209 ### ####',
      '210 ### ####',
      '212 ### ####',
      '213 ### ####',
      '214 ### ####',
      '215 ### ####',
      '216 ### ####',
      '217 ### ####',
      '218 ### ####',
      '219 ### ####',
      '220 ### ####',
      '223 ### ####',
      '224 ### ####',
      '225 ### ####',
      '228 ### ####',
      '229 ### ####',
      '231 ### ####',
      '234 ### ####',
      '239 ### ####',
      '240 ### ####',
      '248 ### ####',
      '251 ### ####',
      '252 ### ####',
      '253 ### ####',
      '254 ### ####',
      '256 ### ####',
      '260 ### ####',
      '262 ### ####',
      '267 ### ####',
      '269 ### ####',
      '270 ### ####',
      '272 ### ####',
      '276 ### ####',
      '279 ### ####',
      '281 ### ####',
      '301 ### ####',
      '302 ### ####',
      '303 ### ####',
      '304 ### ####',
      '305 ### ####',
      '307 ### ####',
      '308 ### ####',
      '309 ### ####',
      '310 ### ####',
      '312 ### ####',
      '313 ### ####',
      '314 ### ####',
      '315 ### ####',
      '316 ### ####',
      '317 ### ####',
      '318 ### ####',
      '319 ### ####',
      '320 ### ####',
      '321 ### ####',
      '323 ### ####',
      '325 ### ####',
      '326 ### ####',
      '330 ### ####',
      '331 ### ####',
      '332 ### ####',
      '334 ### ####',
      '336 ### ####',
      '337 ### ####',
      '339 ### ####',
      '341 ### ####',
      '346 ### ####',
      '347 ### ####',
      '350 ### ####',
      '351 ### ####',
      '352 ### ####',
      '360 ### ####',
      '361 ### ####',
      '363 ### ####',
      '364 ### ####',
      '380 ### ####',
      '385 ### ####',
      '386 ### ####',
      '401 ### ####',
      '402 ### ####',
      '404 ### ####',
      '405 ### ####',
      '406 ### ####',
      '407 ### ####',
      '408 ### ####',
      '409 ### ####',
      '410 ### ####',
      '412 ### ####',
      '413 ### ####',
      '414 ### ####',
      '415 ### ####',
      '417 ### ####',
      '419 ### ####',
      '423 ### ####',
      '424 ### ####',
      '425 ### ####',
      '430 ### ####',
      '432 ### ####',
      '434 ### ####',
      '435 ### ####',
      '440 ### ####',
      '442 ### ####',
      '443 ### ####',
      '445 ### ####',
      '447 ### ####',
      '448 ### ####',
      '458 ### ####',
      '463 ### ####',
      '464 ### ####',
      '469 ### ####',
      '470 ### ####',
      '472 ### ####',
      '475 ### ####',
      '478 ### ####',
      '479 ### ####',
      '480 ### ####',
      '484 ### ####',
      '501 ### ####',
      '502 ### ####',
      '503 ### ####',
      '504 ### ####',
      '505 ### ####',
      '507 ### ####',
      '508 ### ####',
      '509 ### ####',
      '510 ### ####',
      '512 ### ####',
      '513 ### ####',
      '515 ### ####',
      '516 ### ####',
      '517 ### ####',
      '518 ### ####',
      '520 ### ####',
      '530 ### ####',
      '531 ### ####',
      '534 ### ####',
      '539 ### ####',
      '540 ### ####',
      '541 ### ####',
      '551 ### ####',
      '557 ### ####',
      '559 ### ####',
      '561 ### ####',
      '562 ### ####',
      '563 ### ####',
      '564 ### ####',
      '567 ### ####',
      '570 ### ####',
      '571 ### ####',
      '572 ### ####',
      '573 ### ####',
      '574 ### ####',
      '575 ### ####',
      '580 ### ####',
      '582 ### ####',
      '585 ### ####',
      '586 ### ####',
      '601 ### ####',
      '602 ### ####',
      '603 ### ####',
      '605 ### ####',
      '606 ### ####',
      '607 ### ####',
      '608 ### ####',
      '609 ### ####',
      '610 ### ####',
      '612 ### ####',
      '614 ### ####',
      '615 ### ####',
      '616 ### ####',
      '617 ### ####',
      '618 ### ####',
      '619 ### ####',
      '620 ### ####',
      '623 ### ####',
      '626 ### ####',
      '628 ### ####',
      '629 ### ####',
      '630 ### ####',
      '631 ### ####',
      '636 ### ####',
      '640 ### ####',
      '641 ### ####',
      '646 ### ####',
      '650 ### ####',
      '651 ### ####',
      '656 ### ####',
      '657 ### ####',
      '659 ### ####',
      '660 ### ####',
      '661 ### ####',
      '662 ### ####',
      '667 ### ####',
      '669 ### ####',
      '678 ### ####',
      '680 ### ####',
      '681 ### ####',
      '682 ### ####',
      '689 ### ####',
      '701 ### ####',
      '702 ### ####',
      '703 ### ####',
      '704 ### ####',
      '706 ### ####',
      '707 ### ####',
      '708 ### ####',
      '712 ### ####',
      '713 ### ####',
      '714 ### ####',
      '715 ### ####',
      '716 ### ####',
      '717 ### ####',
      '718 ### ####',
      '719 ### ####',
      '720 ### ####',
      '724 ### ####',
      '725 ### ####',
      '726 ### ####',
      '727 ### ####',
      '731 ### ####',
      '732 ### ####',
      '734 ### ####',
      '737 ### ####',
      '740 ### ####',
      '743 ### ####',
      '747 ### ####',
      '754 ### ####',
      '757 ### ####',
      '760 ### ####',
      '762 ### ####',
      '763 ### ####',
      '765 ### ####',
      '769 ### ####',
      '770 ### ####',
      '771 ### ####',
      '772 ### ####',
      '773 ### ####',
      '774 ### ####',
      '775 ### ####',
      '779 ### ####',
      '781 ### ####',
      '785 ### ####',
      '786 ### ####',
      '801 ### ####',
      '802 ### ####',
      '803 ### ####',
      '804 ### ####',
      '805 ### ####',
      '806 ### ####',
      '808 ### ####',
      '810 ### ####',
      '812 ### ####',
      '813 ### ####',
      '814 ### ####',
      '815 ### ####',
      '816 ### ####',
      '817 ### ####',
      '818 ### ####',
      '820 ### ####',
      '826 ### ####',
      '828 ### ####',
      '830 ### ####',
      '831 ### ####',
      '832 ### ####',
      '835 ### ####',
      '838 ### ####',
      '839 ### ####',
      '840 ### ####',
      '843 ### ####',
      '845 ### ####',
      '847 ### ####',
      '848 ### ####',
      '850 ### ####',
      '854 ### ####',
      '856 ### ####',
      '857 ### ####',
      '858 ### ####',
      '859 ### ####',
      '860 ### ####',
      '862 ### ####',
      '863 ### ####',
      '864 ### ####',
      '865 ### ####',
      '870 ### ####',
      '872 ### ####',
      '878 ### ####',
      '901 ### ####',
      '903 ### ####',
      '904 ### ####',
      '906 ### ####',
      '907 ### ####',
      '908 ### ####',
      '909 ### ####',
      '910 ### ####',
      '912 ### ####',
      '913 ### ####',
      '914 ### ####',
      '915 ### ####',
      '916 ### ####',
      '917 ### ####',
      '918 ### ####',
      '919 ### ####',
      '920 ### ####',
      '925 ### ####',
      '928 ### ####',
      '929 ### ####',
      '930 ### ####',
      '931 ### ####',
      '934 ### ####',
      '936 ### ####',
      '937 ### ####',
      '938 ### ####',
      '940 ### ####',
      '941 ### ####',
      '943 ### ####',
      '945 ### ####',
      '947 ### ####',
      '948 ### ####',
      '949 ### ####',
      '951 ### ####',
      '952 ### ####',
      '954 ### ####',
      '956 ### ####',
      '959 ### ####',
      '970 ### ####',
      '971 ### ####',
      '972 ### ####',
      '973 ### ####',
      '978 ### ####',
      '979 ### ####',
      '980 ### ####',
      '983 ### ####',
      '984 ### ####',
      '985 ### ####',
      '986 ### ####',
      '989 ### ####',
    ],
  },
  {
    name: 'Uzbekistan',
    cca2: 'UZ',
    flag: '🇺🇿',
    callingCode: '+998',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Vatican City',
    cca2: 'VA',
    flag: '🇻🇦',
    callingCode: '+39',
    phoneMasks: ['06 698#####'],
  },
  {
    name: 'Saint Vincent and the Grenadines',
    cca2: 'VC',
    flag: '🇻🇨',
    callingCode: '+1',
    phoneMasks: ['784 ### ####'],
  },
  {
    name: 'Venezuela',
    cca2: 'VE',
    flag: '🇻🇪',
    callingCode: '+58',
    phoneMasks: ['### ### ####'],
  },
  {
    name: 'Vietnam',
    cca2: 'VN',
    flag: '🇻🇳',
    callingCode: '+84',
    phoneMasks: ['### #### ###'],
  },
  {
    name: 'Vanuatu',
    cca2: 'VU',
    flag: '🇻🇺',
    callingCode: '+678',
    phoneMasks: ['#####', '## #####'],
  },
  {
    name: 'Samoa',
    cca2: 'WS',
    flag: '🇼🇸',
    callingCode: '+685',
    phoneMasks: ['## ####'],
  },
  {
    name: 'Yemen',
    cca2: 'YE',
    flag: '🇾🇪',
    callingCode: '+967',
    phoneMasks: ['# ### ###', '## ### ###', '### ### ###'],
  },
  {
    name: 'South Africa',
    cca2: 'ZA',
    flag: '🇿🇦',
    callingCode: '+27',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Zambia',
    cca2: 'ZM',
    flag: '🇿🇲',
    callingCode: '+260',
    phoneMasks: ['## ### ####'],
  },
  {
    name: 'Zimbabwe',
    cca2: 'ZW',
    flag: '🇿🇼',
    callingCode: '+263',
    phoneMasks: ['# ######'],
  },
];
